fan: Advance consistent point in high-rate scenario
cockroachdb/cdc-sink pull request #114
Opened 2022-04-07 16:46 UTC by bobvawter

The existing code would never execute the onConsistent callback if the bucket
never becomes idle.

2022-04-07 19:39 UTC, BramGruneir requested changes
Test please?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/114#-:-N-4XLpk826oN9AFh2vH:bx5tzfw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sravotto)



<!-- Sent from Reviewable.io -->

2022-04-07 20:10 UTC, bobvawter commented
The test's name is "Silvano". He was doing some load-testing and this was a quick fix.  Added a code test that loads up the Fan with mutations and makes sure we do start seeing consistent-point updates.

2022-04-08 14:10 UTC, sravotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/114#-:-N-8VcVL4mrK1jsC8BB5:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobvawter)



<!-- Sent from Reviewable.io -->

2022-04-15 16:36 UTC, BramGruneir approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobvawter)



<!-- Sent from Reviewable.io -->

2022-04-15 16:36 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/114#-:-N-i4KAZE0eYY4TPzx0H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobvawter)



<!-- Sent from Reviewable.io -->

2022-04-25 12:23 UTC, merged