logical replication from MySQL
cockroachdb/cdc-sink pull request #116
Opened 2022-04-25 16:58 UTC by sravotto

This change adds initial support for logical replication from a MySQL server.
 It implements a transaction-based replication feed using global transaction identifiers (GTIDs).
  
Summary of changes:

- mylogical:  row level replication feed using global transaction identifiers (GTIDs).   See https://dev.mysql.com/doc/refman/8.0/en/replication-gtids.html
- logical: adding support for persisting replication state in the target database.

2022-04-25 19:42 UTC, bobvawter requested changes
I know this is still a work in progress; my main feedback here is about the API that `logical` should expose to the `Dialect` implementations.  The need to save and restore the consistent point seems like it should just be handled by the logical loop (and maybe the pglogical code just ignores it, since it's tracked server-side).

> Reviewed 4 of 16 files at r1, 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-:-N0XEPN82eZmz1LDv61m:b-wvh8u5)* status: 24 of 25 files reviewed, 14 unresolved discussions (waiting on @bobvawter, @BramGruneir, and @sravotto)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X7f1C31ljjXvzOk4Y):*
This base commit is a bit stale.  The current one is rebased onto master after merging PR #114 .  I had found and fixed the same race condition that you addressed, so you can unwind at least some of your test changes in the logical package.
___
*[`.github/docker-compose.yml` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X89FoC2QSfhD7Vjvu:-N0X89FoC2QSfhD7Vjvv:b-qckk34) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/62299ff7c1c7dae774202ee1d9738e76a51789bd/.github/docker-compose.yml#L24)):*
> ```YAML
>     command: start-single-node --insecure
>   mysql-v8:
>     image: mysql:8-debian
> ```

Please keep the Debian base image.
___
*[`internal/cmd/mylogical/mylogical.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X8l1Y9ftDq2-OoDeH:-N0X8l1Y9ftDq2-OoDeI:b-wyl45b) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/cmd/mylogical/mylogical.go#L75)):*
> ```Go
> // metricsServer starts a trivial prometheus endpoint server which runs
> // until the context is canceled.
> func metricsServer(bindAddr string) error {
> ```

I'll add a todo item to extract the common parts of the logical subcommands into a support package.
___
*[`internal/source/logical/checkpoint.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X95TN8-0Kh-FbyLcj:-N0X95TN8-0Kh-FbyLck:b-xq1kvh) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/logical/checkpoint.go#L26)):*
> ```Go
> // A checkpoint is specific for a particular source,
> // identified by a key that should be universally unique
> type Checkpoint struct {
> ```

I'm trying to keep any code which executes sql commands within the `target` or `util` packages.  This type is a pretty generic string-string mapping, maybe call it `Memo` instead?  It should also have its own test cases as well.
___
*[`internal/source/logical/dialect.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XANI62FB9deqbafWE:-N0XANI62FB9deqbafWF:b-tzvnyq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/logical/dialect.go#L81)):*
> ```Go
> 	GetTargetDB() ident.Ident
> 	// RestoreConsistentPoint restores the state saved into the target database
> 	RestoreConsistentPoint(ctx context.Context, t stamp.Stamp) error
> ```

Why does this API exist?  If the consistent point needs to be tracked by the logical loop, that should happen without the involvement of the Dialect.
___
*[`internal/source/mylogical/config.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBJ-D5JbvS1WzMMkJ:-N0XBJ-EBh_7F3m2gHP2:b-spx7p7) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/config.go#L84)):*
> ```Go
> 		return errors.New("no ServerID was configured")
> 	}
> 	u, err := dburl.Parse(c.SourceConn)
> ```

What does this API do differently from the regular `url.Parse`?
___
*[`internal/source/mylogical/conn.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBUS426YXWa-IQAda:-N0XBUS426YXWa-IQAdb:bej1ph1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L37)):*
> ```Go
> 
> // lsnStamp adapts the LSN offset type to a comparable Stamp value.
> type lsnStamp int64
> ```

I think the base type needs to be a GTIDSet, not just the sequence number, since the target mysql instance could be aggregating changes from multiple upstream servers.  Either way, the type probably needs a name other than `lsn`, since that's a postgres-ism.
___
*[`internal/source/mylogical/conn.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBqZ9-64sCvdEJj3-:-N0XBqZ9-64sCvdEJj30:b-vnpeep) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L48)):*
> ```Go
> func (s lsnStamp) Less(other stamp.Stamp) bool { return s < other.(lsnStamp) }
> 
> func (s lsnStamp) Marshall() string { return strconv.FormatInt(int64(s), 10) }
> ```

The canonical interface for this kind of behavior is https://pkg.go.dev/encoding#TextMarshaler

IIRC, implementing that interface makes a type directly usable by the `db/sql` and `pgx` packages as a parameter value.
___
*[`internal/source/mylogical/conn.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCE6vDSxve98HP_YI:-N0XCE6vDSxve98HP_YJ:b-uytnfk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L62)):*
> ```Go
> 	columns map[ident.Table][]types.ColData
> 	// Last GTIDEvent
> 	lastGTIDEvent int64
> ```

This should probably be an appropriately-typed `Stamp`, not a raw number.
___
*[`internal/source/mylogical/conn.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCNBx4JyqNM97TxkJ:-N0XCNBx4JyqNM97TxkK:bambo7g) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L81)):*
> ```Go
> )
> 
> func (s MutationType) String() string {
> ```

Use stringer instead. See https://github.com/cockroachdb/cdc-sink/blob/master/internal/util/ident/ident.go#L50 for an example.  The nice thing about that helper is that the generate code will fail to compile if it's ever out of date.
___
*[`internal/source/mylogical/conn.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCiZd-ehI9lMoCjz8:-N0XCiZd-ehI9lMoCjz9:b-hef2s5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L87)):*
> ```Go
> var _ logical.Dialect = (*Conn)(nil)
> 
> // NewConn constructs a new pglogical replication feed.
> ```

s/pglogical/mysql/
___
*[`internal/source/mylogical/conn.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCmqp5N-AQQYzvq4z:-N0XCmqp5N-AQQYzvq5-:bgfhjar) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L160)):*
> ```Go
> 				// and the smallest nonzero transaction sequence number not yet used on this server (GNO)
> 				log.Tracef("GTIDEvent %d \n", e.GNO)
> 				c.lastGTIDEvent = e.GNO
> ```

The GNO is only unique from a specific source id, so I think you need to convert this to an actual GTID.

Can't the GTIDEvent trigger the call to `OnBegin()`?  If statement replication isn't enabled, then you aren't guaranteed to see the `QueryEvent` below.
___
*[`internal/util/stamp/stamp.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XDypa6eCA7pUHbx84:-N0XDypa6eCA7pUHbx85:bl9fuo4) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/util/stamp/stamp.go#L23)):*
> ```Go
> 	// Stamp.
> 	Less(other Stamp) bool
> 	Marshall() string
> ```

If this is really necessary to add to `Stamp`, embed the `encoding.TextMarshaler` interface instead.
___
*[`internal/util/stamp/stamp.go` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink [...]

2022-04-28 17:57 UTC, sravotto reviewed
Made changes to move the consistent point impl within the logical loop.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-:-N0lJPbN857wQbJigNiX:bu34hnx)* status: 0 of 29 files reviewed, 14 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X7f1C31ljjXvzOk4Y):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This base commit is a bit stale.  The current one is rebased onto master after merging PR #114 .  I had found and fixed the same race condition that you addressed, so you can unwind at least some of your test changes in the logical package.
</blockquote></details>

Done
___
*[`.github/docker-compose.yml` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X89FoC2QSfhD7Vjvu:-N0lHy-g2577VTscJugk:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/62299ff7c1c7dae774202ee1d9738e76a51789bd/.github/docker-compose.yml#L24)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Please keep the Debian base image.
</blockquote></details>

Done.
___
*[`internal/cmd/mylogical/mylogical.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X8l1Y9ftDq2-OoDeH:-N0lI-f-BFo5rBUWrWOO:b32w0x) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/cmd/mylogical/mylogical.go#L75)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I'll add a todo item to extract the common parts of the logical subcommands into a support package.
</blockquote></details>

OK
___
*[`internal/source/logical/dialect.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XANI62FB9deqbafWE:-N0lI7-t-aiDnj5m72uI:b363lxw) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/logical/dialect.go#L81)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why does this API exist?  If the consistent point needs to be tracked by the logical loop, that should happen without the involvement of the Dialect.
</blockquote></details>

Done - moved the code within the logical loop
___
*[`internal/source/mylogical/config.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBJ-D5JbvS1WzMMkJ:-N0lIKit7M-JtgQgdN-F:bzbpaj8) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/config.go#L84)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

What does this API do differently from the regular `url.Parse`?
</blockquote></details>

Done. Using url.Parse intead.
___
*[`internal/source/mylogical/conn.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBUS426YXWa-IQAda:-N0lIQ3U6JJpoIBWOrxy:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L37)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I think the base type needs to be a GTIDSet, not just the sequence number, since the target mysql instance could be aggregating changes from multiple upstream servers.  Either way, the type probably needs a name other than `lsn`, since that's a postgres-ism.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/conn.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBqZ9-64sCvdEJj3-:-N0lJH4H1rL9qNSfg1k7:b-8l9sc2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L48)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The canonical interface for this kind of behavior is https://pkg.go.dev/encoding#TextMarshaler

IIRC, implementing that interface makes a type directly usable by the `db/sql` and `pgx` packages as a parameter value.
</blockquote></details>

Using fmt.Stringer.
___
*[`internal/source/mylogical/conn.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCE6vDSxve98HP_YI:-N0lISM11wkPo1I0rrHr:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L62)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This should probably be an appropriately-typed `Stamp`, not a raw number.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/conn.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCNBx4JyqNM97TxkJ:-N0lIU5E1hks97w8e63f:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L81)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Use stringer instead. See https://github.com/cockroachdb/cdc-sink/blob/master/internal/util/ident/ident.go#L50 for an example.  The nice thing about that helper is that the generate code will fail to compile if it's ever out of date.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/conn.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCiZd-ehI9lMoCjz8:-N0lIVEA-KIoOxZu0eDE:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L87)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

s/pglogical/mysql/
</blockquote></details>

Done.
___
*[`internal/source/mylogical/conn.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XCmqp5N-AQQYzvq4z:-N0lI_rK4rAwg7lc8V5-:bmw3168) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L160)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The GNO is only unique from a specific source id, so I think you need to convert this to an actual GTID.

Can't the GTIDEvent trigger the call to `OnBegin()`?  If statement replication isn't enabled, then you aren't guaranteed to see the `QueryEvent` below.
</blockquote></details>

It seems that we do need to check for BEGIN - See https://dev.mysql.com/blog-archive/taking-advantage-of-new-transaction-length-metadata/

I did convert the GNO to a GTID
___
*[`internal/util/stamp/stamp.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XDypa6eCA7pUHbx84:-N0lJ00aDXvsuCiEWsNx:bnsr1pw) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/util/stamp/stamp.go#L23)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If this is really necessary to add to `Stamp`, embed the `encoding.TextMarshaler` interface instead.
</blockquote></details>

Decided to use fmt.Stringer
___
*[`internal/util/stamp/stamp.go` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XDlAy-EZr4zjYdyPR:-N0lJ8xY04cTA5oVe5SV:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/util/stamp/stamp.go#L24)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Shouldn't `Unmarshall()` be part of `logical.Dialect` a-la `Dialect.UnmarshalStamp()`? 
</blockquote></details>

Done.
___
*[`internal/source/logical/checkpoint.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0X95TN8-0Kh-FbyLcj:-N0lJDIIBJW2bpPb2ixc:bb6un1j) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/logical/checkpoint.go#L26)):*
<detail [...]

2022-04-29 14:42 UTC, bobvawter requested changes
> Reviewed 2 of 25 files at r4, 27 of 27 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/116)* status: all files reviewed, 41 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/logical/dialect.go` line 43 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pZUh06GX_EJVXaxGs:-N0pZUh06GX_EJVXaxGt:b4b0xfz) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/dialect.go#L43)):*
> ```Go
> 
> 	// UnmarshalStamp decodes a stamp in string format to a stamp.Stamp.
> 	UnmarshalStamp(stamp string) (stamp.Stamp, error)
> ```

The canonical datatype for serialized data is `[]byte`.
___
*[`internal/source/logical/logical.go` line 44 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pZkcQCDAuMBDMUrHS:-N0pZkcQCDAuMBDMUrHT:b-1yaz4i) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L44)):*
> ```Go
> type impl struct {
> 	// Optional checkpoint saved into the target database
> 	memo *memo.Memo
> ```

nit: Alphabetize members.
___
*[`internal/source/logical/logical.go` line 80 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pZrG87K7ejZMwF2Kt:-N0pZrG87K7ejZMwF2Ku:b-yc0q6w) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L80)):*
> ```Go
> 
> var (
> 	standbyTimeout time.Duration = time.Second * 5
> ```

nits: this is usually written `x * duration`. The type declarations are also redundant, since you're not asserting a variable type that's different from the expression type.  Alphabetize as well.
___
*[`internal/source/logical/logical.go` line 137 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0p_moR7AfNHDrjOXuE:-N0p_moR7AfNHDrjOXuF:b-i9gbkl) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L137)):*
> ```Go
> 		targetDB:   config.TargetDB,
> 		memo:       m,
> 		sourceID:   config.ConsistentPointKey,
> ```

`sourceID` vs `ConsistentPointKey` seems mis-named here.
___
*[`internal/source/logical/logical.go` line 141 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0p_gHkAdsjjHHaEbJF:-N0p_gHkAdsjjHHaEbJG:bddmytq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L141)):*
> ```Go
> 			sync.Mutex
> 			consistentPoint stamp.Stamp
> 		}{},
> ```

This `mu` assignment is a no-op.
___
*[`internal/source/logical/logical.go` line 145 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pa2l3-tEb-4Dx1OPB:-N0pa2l3-tEb-4Dx1OPC:b-srgw4z) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L145)):*
> ```Go
> 	}
> 
> 	if cp != "" {
> ```

Move the `if config.ConsistentPointKey != ""` block down here, to reduce the total number of conditional blocks to have to think about.
___
*[`internal/source/logical/logical.go` line 196 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0paFWG68vdl5Duyzqk:-N0paFWG68vdl5Duyzql:bf70gdj) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L196)):*
> ```Go
> }
> 
> func retrieveConsistentPoint(
> ```

This seems like it should also be a member method.
___
*[`internal/source/logical/logical.go` line 272 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0paYd340gd7cpVwg8J:-N0paYd340gd7cpVwg8K:b-dhfot4) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L272)):*
> ```Go
> 		err = l.saveConsistentPoint(ctx)
> 		if err != nil {
> 			return errors.WithStack(err)
> ```

I've been using `errors.WithStack()` only on calls to external modules and assuming that any error coming from code within cdc-sink is already usefully annotated.
___
*[`internal/source/mylogical/config.go` line 43 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbCQH30JTwtQDHHDU:-N0pbCQI-Kyw0CAAOvsh:b-tcvwpj) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L43)):*
> ```Go
> 	caPem, certPem, keyPem []byte, insecureSkipVerify bool, serverName string,
> ) (*tls.Config, error) {
> 	pool := x509.NewCertPool()
> ```

Consider initializing the pool from `x509.SystemCertPool()`?
___
*[`internal/source/mylogical/config.go` line 93 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbR5E37yqbyxKctIu:-N0pbR5E37yqbyxKctIv:bfbg7vz) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L93)):*
> ```Go
> 	params := u.Query()
> 	sslmode := params.Get("sslmode")
> 	// TODO add Tlssupport
> ```

Isn't this done?
___
*[`internal/source/mylogical/config.go` line 98 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbTly3c4B_yf_cPux:-N0pbTly3c4B_yf_cPuy:b4ofpys) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L98)):*
> ```Go
> 	switch sslmode {
> 	case "disable":
> 		tls = nil
> ```

This is a no-op, just add a comment here.
___
*[`internal/source/mylogical/config.go` line 100 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbqtJ4ptyrukTe08V:-N0pbqtJ4ptyrukTe08W:b-seoqx5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L100)):*
> ```Go
> 		tls = nil
> 	case "require", "verify-ca", "verify-full":
> 		caCert, err := ioutil.ReadFile(params.Get("sslrootcert"))
> ```

This would read better the guts of this case statement were extracted into a separate function or pushed down into `newClientTLSConfig`.
___
*[`internal/source/mylogical/config.go` line 120 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbXOhEhT7JnKfLeju:-N0pbXOhEhT7JnKfLejv:b-sc6suq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L120)):*
> ```Go
> 		}
> 	default:
> 		return errors.New("invalid sslmode")
> ```

`erorrs.Errorf("invalid sslmode: %q", sslmode)`
___
*[`internal/source/mylogical/config.go` line 126 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pc1s8-g3OwZcQLkZ9:-N0pc1s8-g3OwZcQLkZA:b-65ul8c) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L126)):*
> ```Go
> 	cfg := replication.BinlogSyncerConfig{
> 		ServerID:  uint32(serverID),
> 		Flavor:    "mysql",
> ```

Just a heads-up, but we do have an upcoming customer commit to support MariaDB, but let's do that in a separate PR.
___
*[`internal/source/mylogical/config.go` line 134 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pcCDD85Iaa8rHPwCX:-N0pcCDD85Iaa8rHPwCY:bkk7pau) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L134)):*
> ```Go
> 	}
> 
> 	c.binlogSyncerConfig = cfg
> ```

No need for the separate local variable.
___
*[`internal/source/mylogical/conn.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBqZ9-64sCvdEJj3-:-N0pcPr6BZEg_LjPvAu7:b-tw51e6) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L48)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Using fmt.Stringer.
</blockquote></details>

`fmt.Stringer` is not the right interface for persistence use.  `Stringer` is intended for producing human-readable [...]

2022-05-02 15:08 UTC, sravotto reviewed
Thanks for the review. I made additional changes, and added a test for mysql types.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-:-N14Iyae5A_G1tin00Ra:bly1dwg)* status: 11 of 30 files reviewed, 37 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/logical/dialect.go` line 43 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pZUh06GX_EJVXaxGs:-N14GMc_2LCE0ybdCCl7:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/dialect.go#L43)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The canonical datatype for serialized data is `[]byte`.
</blockquote></details>

Done.
___
*[`internal/source/logical/logical.go` line 80 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pZrG87K7ejZMwF2Kt:-N14GRobEWk3vNBn9UAP:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L80)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

nits: this is usually written `x * duration`. The type declarations are also redundant, since you're not asserting a variable type that's different from the expression type.  Alphabetize as well.
</blockquote></details>

Done.
___
*[`internal/source/logical/logical.go` line 137 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0p_moR7AfNHDrjOXuE:-N14GVnc3zVatPSAdQCx:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L137)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`sourceID` vs `ConsistentPointKey` seems mis-named here.
</blockquote></details>

Done.
___
*[`internal/source/logical/logical.go` line 141 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0p_gHkAdsjjHHaEbJF:-N14GXAI-pPrzIMtX9f-:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L141)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This `mu` assignment is a no-op.
</blockquote></details>

Done.
___
*[`internal/source/logical/logical.go` line 145 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pa2l3-tEb-4Dx1OPB:-N14Iq5E9-Vr1Cwo2gWK:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L145)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Move the `if config.ConsistentPointKey != ""` block down here, to reduce the total number of conditional blocks to have to think about.
</blockquote></details>

Done.
___
*[`internal/source/logical/logical.go` line 196 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0paFWG68vdl5Duyzqk:-N14Gk1z09gph-3xyIhi:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L196)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This seems like it should also be a member method.
</blockquote></details>

Done.
___
*[`internal/source/logical/logical.go` line 272 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0paYd340gd7cpVwg8J:-N14Gm562SE-cKZmdzUf:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/logical/logical.go#L272)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I've been using `errors.WithStack()` only on calls to external modules and assuming that any error coming from code within cdc-sink is already usefully annotated.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/config.go` line 43 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbCQH30JTwtQDHHDU:-N14GonY0dpzFtI7HVYk:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L43)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Consider initializing the pool from `x509.SystemCertPool()`?
</blockquote></details>

Done.
___
*[`internal/source/mylogical/config.go` line 93 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbR5E37yqbyxKctIu:-N14Gpxl1KmDpwao_vWb:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L93)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Isn't this done?
</blockquote></details>

Done.
___
*[`internal/source/mylogical/config.go` line 98 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbTly3c4B_yf_cPux:-N14Gqy5DNvcGsXmTg67:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L98)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This is a no-op, just add a comment here.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/config.go` line 100 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbqtJ4ptyrukTe08V:-N14Grnj-29IvFokM7c2:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L100)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This would read better the guts of this case statement were extracted into a separate function or pushed down into `newClientTLSConfig`.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/config.go` line 120 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pbXOhEhT7JnKfLeju:-N14Gt631gnHM2zxfxq7:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L120)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`erorrs.Errorf("invalid sslmode: %q", sslmode)`
</blockquote></details>

Done.
___
*[`internal/source/mylogical/config.go` line 126 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pc1s8-g3OwZcQLkZ9:-N14GuMu3gixF9abgyrr:b-k7huu1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L126)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Just a heads-up, but we do have an upcoming customer commit to support MariaDB, but let's do that in a separate PR.
</blockquote></details>

Ok - Sounds good.
___
*[`internal/source/mylogical/config.go` line 134 at r5](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0pcCDD85Iaa8rHPwCX:-N14H2r8EmWd56uROwJp:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/56f18f1d9fe7d8468724854c72a397100da6cab4/internal/source/mylogical/config.go#L134)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

No need for the separate local variable.
</blockquote></details>

Done.
___
*[`internal/source/mylogical/conn.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N0XBqZ9-64sCvdEJj3-:-N14H5g7DgXt0gz18Qdl:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/42c379cdb299a417036b1c5a082db3bc86666a69/internal/source/mylogical/conn.go#L48)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`fmt.Stringer` is not the right interface for persistence use.  `Stringer` is intended for producing human-readable representations of the d [...]

2022-05-02 19:41 UTC, bobvawter approved these changes
:shipit: Looks good, let's go ahead and commit this.  The next point of work will be to add MariaDB support to the code.

> Reviewed 19 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-:-N15HVSn2_Bp2P4FwUe8:b-b1fvs6)* status: all files reviewed, 8 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/logical/logical.go` line 63 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N159Pkf66uexab6GTHT:-N159Pkf66uexab6GTHU:bkc4pzb) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/logical/logical.go#L63)):*
> ```Go
> 	serializer *serial.Pool
> 	// the key used to persist the consistentPoint stamp.
> 	consistentPointKey string
> ```

nit: Alphabetize
___
*[`internal/source/logical/logical.go` line 67 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N159RN_8LXMHGpp3rjC:-N159RN_8LXMHGpp3rjD:bx8osqg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/logical/logical.go#L67)):*
> ```Go
> 	targetDB ident.Ident
> 	// targetPool
> 	targetPool pgxtype.Querier
> ```

nit: Update the comment what the pool is used for.
___
*[`internal/source/logical/logical.go` line 78 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N159a9u0cmieFNzPB4P:-N159a9u0cmieFNzPB4Q:b-q3fhjn) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/logical/logical.go#L78)):*
> ```Go
> 	}
> 
> 	standbyDeadline time.Time
> ```

nit: Add a comment and re-order the field.
___
*[`internal/source/logical/logical.go` line 184 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N15AIlQ2qqLLJ-XO344:-N15AIlRDwtSK3HFbrah:b-w77m5t) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/logical/logical.go#L184)):*
> ```Go
> }
> 
> func (l *impl) saveConsistentPoint(ctx context.Context, tx pgxtype.Querier) error {
> ```

Passing the querier into `save` and `retrieve` is redundant if they're only ever receiving `l.targetPool`.
___
*[`internal/source/mylogical/conn.go` line 102 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N15CbuIAJno7mgeRVKA:-N15CbuIAJno7mgeRVKB:b-8clm0y) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/mylogical/conn.go#L102)):*
> ```Go
> 	insert
> 	update
> 	delete
> ```

This declaration would shadow the language's built-in `delete` function, used to remove elements from a map.  It's probably worth renaming these declarations to be `xyzMutation` to avoid naming conflicts elsewhere.
___
*[`internal/source/mylogical/conn.go` line 343 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N15El-MEVcKFWQ6EGyC:-N15El-MEVcKFWQ6EGyD:behwtyc) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/mylogical/conn.go#L343)):*
> ```Go
> 		for idx, sourceCol := range row {
> 			targetCol := targetCols[idx]
> 			switch targetCol.Type {
> ```

Switching on `targetCol.Type` is ok, but would it make more sense to switch instead on sourceCol's type? This would reduce the amount of code duplication below.

```
switch v := sourceCol.type {
  case nil:
  case []byte:
  case int64:
  default:
}
```

Then, in the `[]byte` and `int64` case, add a sanity check on `sourceCol.Type` to return an error if there's an unexpected value.
___
*[`internal/source/mylogical/conn.go` line 377 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N15EOd-7maBirGzvdwp:-N15EOd02fOlX8xghd0I:b-jwl3fw) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/source/mylogical/conn.go#L377)):*
> ```Go
> 		// on update we only care about the new value.
> 		// even rows are skipped since they contain the value before the update
> 		if operation == update && (rowNum%2 == 0) {
> ```

Can this check move the the top loop, to avoid doing all of that decoding, only to throw away the work?
___
*[`internal/types/types.go` line 103 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/116#-N15GJAz6H8ZIMcUGWV5:-N15GJAz6H8ZIMcUGWV6:b-i71jfp) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f8a2177bb15ea3854f750b49bae89bac7431e7c8/internal/types/types.go#L103)):*
> ```Go
> 	Name    ident.Ident
> 	Primary bool
> 	Type    interface{}
> ```

Why is this `interface{}` ?  Document the types that might be expected.


<!-- Sent from Reviewable.io -->

2022-05-02 22:52 UTC, merged