cdc-sink: Convert to pgx library
cockroachdb/cdc-sink pull request #40
Opened 2021-07-25 21:52 UTC by bobvawter

This change converts cdc-sink to use the pgx API directly. The tests are green against 21.1.6.

2021-07-26 15:56 UTC, BramGruneir requested changes
Looks good overall, just a few minor questions.

2021-07-26 15:56 UTC, BramGruneir commented on main_test.go
> +func loopUntilSync(
Please add a comment here. Just to describe what sync means.

2021-07-26 15:56 UTC, BramGruneir commented on main_test.go
> +func loopUntilMaxB(
commend here please

2021-07-26 15:56 UTC, BramGruneir commented on main_test.go
> +		//		{`geography`, `GEOGRAPHY`, `0101000020E6100000000000000000F03F0000000000000040`, false},
Geospatials don't work?

2021-07-26 15:56 UTC, BramGruneir commented on main_test.go
> +				if count > 0 {
`> 0` is different than `!= 1`  Could it have more than one, if it doesn't, isn't that an error?

2021-07-26 15:56 UTC, BramGruneir commented on main_test.go
> +					a.NoErrorf(table.deleteAll(ctx), "deleting %s", table)
Doesn't this need to return on error?

2021-07-26 15:56 UTC, BramGruneir commented on sink.go
> -// cleanValue will check the type of the value being upserted to ensure it
So happy to see this hack removed!

2021-07-26 15:56 UTC, BramGruneir commented on sink_table.go
> +// WriteToSinkTable upserts all lines to the sink table via the COPY protocol.
Much nicer

2021-07-26 15:56 UTC, BramGruneir commented on sink_table.go
> +		[]string{"nanos", "logical", "key", "after"},
Worth making this const?

2021-07-26 15:56 UTC, BramGruneir commented on sinks.go
> +		if err := Retry(ctx, func(ctx context.Context) error {
Does retry handle the crdb specific retires?  Is 'github.com/cockroachdb/cockroach-go/crdb' no longer needed?

2021-07-26 15:56 UTC, BramGruneir commented on util.go
> +// Copyright 2020 The Cockroach Authors.
Should we import this instead?  Or is it not compatible with pgx?

At least mention the providence.

2021-07-27 13:13 UTC, bobvawter commented on main_test.go
> +func loopUntilMaxB(
Done.

2021-07-27 13:13 UTC, bobvawter commented on main_test.go
> +		//		{`geography`, `GEOGRAPHY`, `0101000020E6100000000000000000F03F0000000000000040`, false},
Added a TODO; I can't figure out yet how to get them to re-encode from the server properly.

2021-07-27 13:17 UTC, bobvawter commented on main_test.go
> +				if count > 0 {
Fixed.

2021-07-27 13:19 UTC, bobvawter commented on sink_table.go
> +		[]string{"nanos", "logical", "key", "after"},
Extracted to global variable.

2021-07-27 13:22 UTC, bobvawter commented on util.go
> +// Copyright 2020 The Cockroach Authors.
The cockroach pgx support library doesn't allow for implicit transactions. The specific codes are

```
			case "40001": // Serialization Failure
			case "40003": // Statement Completion Unknown
			case "08003": // Connection Does Not Exist
			case "08006": // Connection Failure
```

The provenance is mentioned at the top of the file, it's from Cacheroach.

2021-07-27 13:23 UTC, bobvawter commented on main.go
> +	handler := http.Handler(http.HandlerFunc(createHandler(db, sinks)))
Fixed.

2021-07-27 13:23 UTC, bobvawter commented on main_test.go
> +func loopUntilSync(
Done.

2021-07-27 15:00 UTC, merged