WIP: apply: Add support for PostgreSQL
cockroachdb/cdc-sink pull request #475
Opened 2023-09-13 21:32 UTC by bobvawter

This change adds support to the apply package for applying mutations to a PostgreSQL database.

2023-09-15 14:57 UTC, BramGruneir commented
I think it might be worthwhile keeping separate templates for each destination.  It means the templates have less extra logic in them and hence are more readable.  Also, weird bugs between versions (of say postgres) won't accidently creep into crdb.

Also, that way crdb can keep the upset, which is a much nicer query.





<!-- Sent from Reviewable.io -->

2023-09-15 15:23 UTC, BramGruneir requested changes
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/475)* status: all files reviewed, 1 unresolved discussion (waiting on @bobvawter and @sravotto)

___
*[`internal/target/apply/apply_test.go` line 590 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/475#-NeOGo89D4LSnMirBeQB:-NeOGo89D4LSnMirBeQC:b-spewjp) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4616a5494e59db2e072e42af332307fd91bee313/internal/target/apply/apply_test.go#L590)):*
> ```Go
> }
> 
> func normalizeJSON(data string) (string, error) {
> ```

Can you just add a quick comment about why this is needed?


<!-- Sent from Reviewable.io -->

2023-09-15 22:02 UTC, bobvawter reviewed
There are now `crdb` and `pg` template directories.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/475#-:-NePqqWeCFgTb1YpFZ9z:bqhynv5)* status: 22 of 33 files reviewed, 1 unresolved discussion (waiting on @BramGruneir and @sravotto)

___
*[`internal/target/apply/apply_test.go` line 590 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/475#-NeOGo89D4LSnMirBeQB:-NePqxzg1FJgwBYaxHXC:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4616a5494e59db2e072e42af332307fd91bee313/internal/target/apply/apply_test.go#L590)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you just add a quick comment about why this is needed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-16 20:05 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/475#-:-NeUaKxg4xIf14dAQB01:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sravotto)



<!-- Sent from Reviewable.io -->

2023-09-18 12:19 UTC, merged