apply: Allow templates to be loaded from disk
cockroachdb/cdc-sink pull request #515
Opened 2023-10-05 16:47 UTC by bobvawter

This change adds an environment variable that allows the golang templates to be loaded from the filesystem, instead of using the ones embedded in the binary. A hidden `cdc-sink dumptemplates` command is added to copy the templates to disk.

The indended use-case for this change is to support in-the-field adjuments to the query templates, without the need to recompile the binary. No long-term compatibility guarantees can be made about the contents and structure of the template files, since they are tightly coupled with internal cdc-sink datastructures.

2023-10-05 18:42 UTC, BramGruneir requested changes
I know it's only for debugging, but a test would be helpful.

And instead of going whole hog, why not only load templates that are present and use the embedded ones otherwise.  (And add a log message to say which is which)

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/515#-:-Ng07V-Z0-B7iuaocVg_:b-5jbd7d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sravotto)



<!-- Sent from Reviewable.io -->

2023-10-05 20:09 UTC, bobvawter reviewed
Added tests. PTAL.

It would be possible to write an `overlayFS` that merges two `fs.FS` together, but that seems like a lot of over-engineering when the total number of files is pretty minimal.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/515#-:-Ng0S8BIELW8XJacehkV:b-8y3eb1)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @BramGruneir and @sravotto)



<!-- Sent from Reviewable.io -->

2023-10-06 03:20 UTC, sravotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/515#-:-Ng2-0Y4-14GWYzAFRQJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobvawter)



<!-- Sent from Reviewable.io -->

2023-10-06 17:35 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/515#-:-Ng52dZC0ErqVMPoe-eM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobvawter)



<!-- Sent from Reviewable.io -->

2023-10-06 20:06 UTC, merged