pglogical: skip empty transactions
cockroachdb/cdc-sink pull request #589
Opened 2023-11-07 22:33 UTC by sravotto

In Postgres older releases (<v15) the walsender sends an empty transaction if all DMLs in the transaction are not published to publication filter.

This change allows cdc-sink to skip these transaction without updating the last consistent point in the memo table. The change is gated behind the --skipEmptyTransactions configuration flag.

2023-11-07 23:07 UTC, BramGruneir requested changes
The change looks good, but needs testing.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-:-Nig1PThCA_Y5hQOekxN:b-oli5nr)* status: all files reviewed, 3 unresolved discussions (waiting on @sravotto)

___
*[`internal/source/pglogical/config.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig0RG0DogAPt1jro_G:-Nig0RG0DogAPt1jro_H:by4lcu1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/config.go#L36)):*
> ```Go
> 	// Skip empty transactions.
> 	// In Postgres version < v15, the stream might contain empty transactions.
> 	// Setting this to true will allow cdc-sink to ignore them.
> ```

Can you add a link to the postgres docs where they fixed this behaviour?
___
*[`internal/source/pglogical/config.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig08A09zAcqArVhPsx:-Nig08A09zAcqArVhPsy:b94qi3l) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/config.go#L51)):*
> ```Go
> 	c.LoopConfig.Bind(f)
> 
> 	f.BoolVar(&c.SkipEmptyTransactions, "skipEmptyTransactions", false, "skip empty transaction in the replication fedd")
> ```

feed not fedd

But really this should be "skip writing to the memo table when transactions have no content"
___
*[`internal/source/pglogical/conn.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig0Yci7f-OuvZt4a1-:-Nig0Yci7f-OuvZt4a10:b-mkv9dw) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/conn.go#L94)):*
> ```Go
> 	ignoreBefore, _ := events.GetConsistentPoint()
> 	ignoreLSN := ignoreBefore.(*lsnStamp).AsLSN()
> 	// On Postgres version before v15, there could be empty transactions,
> ```

Can you reword this?

On Postgres versions before v15, mutations that are not part of the publication slots still product transactions, but they have no content.  See:  xxx for more details.


<!-- Sent from Reviewable.io -->

2023-11-10 16:28 UTC, sravotto reviewed
Please take another look, I added a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-:-Niu2zfcB4W_K-bH8viK:bta1nhq)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @BramGruneir)

___
*[`internal/source/pglogical/config.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig0RG0DogAPt1jro_G:-Niu2qNP8wOrKVXKmX9G:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/config.go#L36)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you add a link to the postgres docs where they fixed this behaviour?
</blockquote></details>

Done.
___
*[`internal/source/pglogical/config.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig08A09zAcqArVhPsx:-Niu2usRDWsbmDiyGP8w:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/config.go#L51)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

feed not fedd

But really this should be "skip writing to the memo table when transactions have no content"
</blockquote></details>

Done.
___
*[`internal/source/pglogical/conn.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig0Yci7f-OuvZt4a1-:-Niu2x3YBl5u6hbLSpmJ:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/conn.go#L94)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you reword this?

On Postgres versions before v15, mutations that are not part of the publication slots still product transactions, but they have no content.  See:  xxx for more details.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 17:23 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Can you just adjust the wording again in that one setting.

> Reviewed 2 of 2 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-:-NiuFYuXA49mkKvHeA-O:bjopkp6)* status: all files reviewed, 1 unresolved discussion (waiting on @sravotto)

___
*[`internal/source/pglogical/config.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig08A09zAcqArVhPsx:-NijVRZy8Z-_8XD14B1e:brzvxz2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/config.go#L51)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

feed not fedd

But really this should be "skip writing to the memo table when transactions have no content"
</blockquote></details>

Upon reading it again, can you make it singular?
"skip writing to the memo table when a transaction has no content"


<!-- Sent from Reviewable.io -->

2023-11-10 18:20 UTC, sravotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/589)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @BramGruneir)

___
*[`internal/source/pglogical/config.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/589#-Nig08A09zAcqArVhPsx:-NiuSbI37aHTaYLtfM7-:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/b4b72eb6ff30e19decc359859deec0aacb194cc8/internal/source/pglogical/config.go#L51)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Upon reading it again, can you make it singular?
"skip writing to the memo table when a transaction has no content"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 18:34 UTC, merged