[WIP] cdc-sink: Overhaul
cockroachdb/cdc-sink pull request #73
Opened 2021-12-13 14:08 UTC by bobvawter

This change overhauls the cdc-sink code to split it into well-defined packages
and APIs.

Notable functional changes:

A cdc-sink endpoint now operates on an entire database at once, since this is
the use-case that has been most prominently.

An "immediate" mode is supported, which applies incoming data without waiting
for resolved timestamps. This is intended for use when backfilling large
datasets or if a high-volume changefeed must catch up after an outage. It is
not expected to be the default configuration for cdc-sink.

Notes to reviewers:

The sinktypes package defines interfaces for the major moving parts of the
revised cdc-sink code base. At present, each interface is implemented by a
single type, but having small APIs has been useful in identifying the
independent parts of cdc-sink.

Similarly, the package structure may be overly fine-grained in favor of
identifying specific, small portions of code that compose easily.

A comment at the top of most files indicates where code was repackaged from.

Recommended package review order:
  sinktypes, cdc/handler, backend/mutation, backend/apply, backend/timestamp

2021-12-16 22:17 UTC, bobvawter commented
I have pushed some revisions based on the desk review yesterday.

* cdc-sink is now based around a single changefeed per `SCHEMA` (i.e. the second-level namespace in each `DATABASE`). The url format for sending changes to cdc-sink now leads with `/targetDB/targetSchema/` to specify the destination table(s).
* The README file has been overhauled to reflect the new state of the code.  I have revalidated the quickstart flow.
* Added support for the new `webhook-https://` scheme in CockroachDB v21.2. cdc-sink can optionally speak TLS.

2021-12-16 22:37 UTC, sravotto reviewed
> Reviewed 18 of 41 files at r1, 18 of 22 files at r3, 1 of 1 files at r5, 5 of 5 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, 24 of 24 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73)* status: all files reviewed, 2 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[internal/sinktypes/sinktypes.go, line 15 at r8](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr2yG-T6XLgLsipJOke:-Mr2yG-T6XLgLsipJOkf:bl7ovmy) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/6c0245cfc1baa734f0219252707b4a92475b0a20/internal/sinktypes/sinktypes.go#L15)):*
> ```Go
> // the types into this package is to make it easy to compose
> // functionality as the cdc-sink project evolves.
> package sinktypes
> ```

Should we call this package simply "types" (or model/interfaces)? 
___
*[internal/sinktypes/sinktypes.go, line 79 at r8](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr33Tp24V4D0ELRrZsl:-Mr33Tp24V4D0ELRrZsm:b-n13jza) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/6c0245cfc1baa734f0219252707b4a92475b0a20/internal/sinktypes/sinktypes.go#L79)):*
> ```Go
> 
> // A TimeSwapper maintains a durable map of string keys to timestamps.
> type TimeSwapper interface {
> ```

Perhaps we can call it TimeKeeper? And the method simply Update?
___
*[internal/util/ident/ident.go, line 12 at r8](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr4C_JN5Krfk6rp6umK:-Mr4C_JN5Krfk6rp6umL:bu285gi) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/6c0245cfc1baa734f0219252707b4a92475b0a20/internal/util/ident/ident.go#L12)):*
> ```Go
> 
> // Package ident contains types for safely representing SQL identifiers.
> package ident
> ```

Like this approach. Makes the (rest of the) code much more robust and easier to read.


<!-- Sent from Reviewable.io -->

2021-12-16 22:50 UTC, bobvawter reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73)* status: 35 of 52 files reviewed, 2 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[internal/sinktypes/sinktypes.go, line 15 at r8](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr2yG-T6XLgLsipJOke:-Mr4R3H63bXM1s4nalxD:b6xm00i) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/6c0245cfc1baa734f0219252707b4a92475b0a20/internal/sinktypes/sinktypes.go#L15)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Should we call this package simply "types" (or model/interfaces)? 
</blockquote></details>

Renamed it to "types".
___
*[internal/sinktypes/sinktypes.go, line 79 at r8](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr33Tp24V4D0ELRrZsl:-Mr4R7iZB9IgKxOEy_jh:b-yo1gbt) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/6c0245cfc1baa734f0219252707b4a92475b0a20/internal/sinktypes/sinktypes.go#L79)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Perhaps we can call it TimeKeeper? And the method simply Update?
</blockquote></details>

Switch it to `TimeKeeper.Put()` since it's map-like and one puts into a map.


<!-- Sent from Reviewable.io -->

2021-12-20 14:45 UTC, BramGruneir commented
___
*[internal/frontend/cdc/resolved.go, line 128 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNIHee8UOto0iCkPAd:-MrNIHee8UOto0iCkPAe:b-uyo6wg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/frontend/cdc/resolved.go#L128)):*
> ```Go
> 		for table := range targetSchema {
> 			// Only perform work on target tables which match the
> 			// database and schema name specified in the resolved URL.
> ```

Do we throw an error if we get one that doesn't match?  A table we were not expecting?


<!-- Sent from Reviewable.io -->

2021-12-20 16:00 UTC, BramGruneir requested changes
> Reviewed 15 of 41 files at r1, 5 of 22 files at r3, 1 of 5 files at r6, 1 of 3 files at r7, 1 of 1 files at r8, 12 of 24 files at r9, 17 of 17 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73)* status: all files reviewed, 36 unresolved discussions (waiting on @bobvawter and @sravotto)

___
*[internal/backend/apply/apply.go, line 162 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8ESRXDXJrJU121TFV:-Mr8ESRXDXJrJU121TFW:bxj74s0) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L162)):*
> ```Go
> 	defer res.Close()
> 
> 	for i, j := 0, batch.Len(); i < j; i++ {
> ```

Is the assignment of j needed here? 
___
*[internal/backend/apply/apply.go, line 194 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8GNft3o0XK_pOo2oy:-Mr8GNft3o0XK_pOo2oz:bfgnj53) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L194)):*
> ```Go
> 			rawColName := col.Name.Raw()
> 			decoded, ok := temp[rawColName]
> 			delete(temp, rawColName)
> ```

These seems slightly out of order.  I think they'll work, (delete something that doesn't exist,) but the logic doesn't flow cleanly.
___
*[internal/backend/apply/apply.go, line 252 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8I2mA6A4ZXwqLshYu:-Mr8I2mB2fbwZYlT4iL1:b-piytqi) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L252)):*
> ```Go
> 	_, _ = fmt.Fprintf(&delete, "DELETE FROM %s WHERE (", a.target)
> 	_, _ = fmt.Fprintf(&upsert, "UPSERT INTO %s (", a.target)
> 	for i := range colData {
> ```

why not 
for i, col := 

cleans up a lot of the colData[i] you're using all over all the place
___
*[internal/backend/apply/apply.go, line 270 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8IF1x-dXm6KNEHPFR:-Mr8IF1x-dXm6KNEHPFS:buo9nmt) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L270)):*
> ```Go
> 	delete.WriteString(") IN (SELECT ")
> 	upsert.WriteString(") SELECT ")
> 	for i := range colData {
> ```

Same here
___
*[internal/backend/apply/factory.go, line 39 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8jNJcDgETyGrElGab:-Mr8jNJcDgETyGrElGac:bw5pm34) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/factory.go#L39)):*
> ```Go
> 
> // Get returns a memoized instance of the Applier for the table.
> func (f *factory) Get(
> ```

I'm a little confused by the api here.

Get and New are the only exposed functions?

Get --> getUnlocked
New --> returns a factory

But no Create?
? --> createUnlocked
___
*[internal/backend/mutation/factory.go, line 43 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8kGWLE1T5Gx9ykqEl:-Mr8kGWLE1T5Gx9ykqEm:b-txkgjt) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/mutation/factory.go#L43)):*
> ```Go
> }
> 
> func (f *factory) createUnlocked(ctx context.Context, table ident.Table) (*store, error) {
> ```

Are createUnlocked and getUnlocked called from anywhere else?  Do you need them to be their own functions?  I'm guessing for unit tests?
___
*[internal/backend/mutation/store.go, line 50 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr92HqyBi5UpmRzcdmj:-Mr92HqyBi5UpmRzcdmk:b10pf61) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/mutation/store.go#L50)):*
> ```Go
> // newStore constructs a new mutation store that will track pending
> // mutations to be applied to the given target table.
> func newStore(
> ```

Shouldn't this be New? 
___
*[internal/backend/mutation/store.go, line 133 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9GMX74HY6on6FZAwT:-Mr9GMX74HY6on6FZAwU:b-tzoljo) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/mutation/store.go#L133)):*
> ```Go
> 	batch := &pgx.Batch{}
> 
> 	for i := range mutations {
> ```

 Why not use for i, mut := range mutations instead of indexing in every time?
___
*[internal/backend/mutation/store_test.go, line 79 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9H6sJ5w2kSgnl3aID:-Mr9H6sJ5w2kSgnl3aIE:b-gdnvt3) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/mutation/store_test.go#L79)):*
> ```Go
> 
> 	// Dequeue.
> 	ret, err := s.Drain(ctx, dbInfo.Pool(),
> ```

style nit,  I thought our usual style was to put only the ctx on the first line then the rest on the 2nd.  Or to put everything on the 2nd line with the close bracket on the 3rd

Hmm... can we get the style guide from cockroach?
___
*[internal/backend/schemawatch/coldata.go, line 37 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9HhCO2dxkzZeR4HZv:-Mr9HhCO2dxkzZeR4HZw:b-yuatzs) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/schemawatch/coldata.go#L37)):*
> ```Go
> // Retrieve the primary key columns in their index-order, then append
> // any remaining non-generated columns.
> const sqlColumnsQuery = `
> ```

Wow... is the most efficient way?  It makes sense but I'm just surprised you need this complex a query.
___
*[internal/backend/schemawatch/coldata_test.go, line 90 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9I76n8JsSN3ULqglt:-Mr9I76o2qOAruNnZxS0:bw2z8qv) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/schemawatch/coldata_test.go#L90)):*
> ```Go
> 
> 	// Virtual columns not supported before v21.1
> 	if !strings.Contains(dbInfo.Version(), "v20.2.") {
> ```

If you have a few more tests that need version numbers, it makes sense to create a utility to determine if the version is newer, older or equal.  Can you just add a comment about how the older version supported is v20.2?  Perhaps that info should go in the readme as well.
___
*[internal/backend/schemawatch/watcher.go, line 48 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9J1s58pDmbR2fTjRw:-Mr9J1s58pDmbR2fTjRx:b-dxkqnt) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/schemawatch/watcher.go#L48)):*
> ```Go
> 	mu struct {
> 		sync.RWMutex
> 		cond sync.Cond // Conditional on the RLocker
> ```

Should cond be under mu if a lock isn't required for its use?
I see it's a weird mixed thing... Just needs a read lock.

So I find this a little confusing.  Simplifying the locking here might be worthwhile.  
___
*[internal/backend/schemawatch/watcher.go, line 112 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9Jp1X88OgOFQPowRt:-Mr9Jp1X88OgOFQPowRu:b8eb92s) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/schemawatch/watcher.go#L112)):*
> ```Go
> 	w.mu.data = data
> 	w.mu.Unlock()
> 	w.mu.cond.Broadcast()
> ```

Why take this out of the lock?
___
*[internal/backend/schemawatch/watcher.go, line 153 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr9K-wl42XAhWTMOk1Q:-Mr9K-wl42XAhWTMOk1R:b897wzu) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/schemawatch/watcher.go#L153)):*
> ```Go
> 			// Respond to context cancellation or dropping the table.
> 			if !ok || ctx.Err() != nil {
> 				return
> ```

Shouldn't this do something with the error?
___
*[internal/backend/schemawatch/watcher_test.go, line 41 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNAela2T7ADGTCfc5r:-MrNAelb-MHEMF3ADEEK: [...]

2021-12-20 16:07 UTC, BramGruneir reviewed
That's a lot of code, I went through it all.  
Not many changes needed I think.

I still don't like the frontend/backend names.  

How about sources/target? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-:-MrNa0ZwADTqoppCZLCg:biv6qr7)* status: all files reviewed, 36 unresolved discussions (waiting on @bobvawter and @sravotto)



<!-- Sent from Reviewable.io -->

2021-12-20 21:48 UTC, bobvawter reviewed
TFTR. PTAL. TANSTAAFL.

Renamed the mid-level packages to to `sources` and `target`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-:-MrNhfq92VLfGZ0CBPMy:bptmlr7)* status: 20 of 55 files reviewed, 36 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[internal/util/batches/batches.go, line 29 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNXCIY11P_TA-nzhy2:-MrOP-M42PUpw4H5guIP:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/util/batches/batches.go#L29)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This is really nice.
</blockquote></details>

Thanks.
___
*[internal/util/batches/batches.go, line 29 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNXSqQDWapkeIl1u4o:-MrORR3uEVHRcpspPlQL:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/util/batches/batches.go#L29)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add tests for batch.
</blockquote></details>

Done.
___
*[internal/util/ident/ident.go, line 79 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNYZJM555H5zdRbY1s:-MrOReLI6iTrvCDvGEzK:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/util/ident/ident.go#L79)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Shouldn't this be IsEmpty() 
</blockquote></details>

Done.
___
*[internal/util/ident/ident.go, line 85 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNYNA1ARmGdeeB9TJL:-MrORxm62h9mIoA5lv0p:b-gjua7q) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/util/ident/ident.go#L85)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not just store the raw?  Because this is clearly a lie :) 
</blockquote></details>

Changed to store both the quoted and the raw, since they're used in pretty much equal proportions throughout the code.
___
*[internal/util/ident/ident_test.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNZ61T6o9pFWF-q7Nd:-MrOTAVREwG0c0LkUPSa:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/util/ident/ident_test.go#L49)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add some more test cases that would produce errors.  Empty schema, empty db, empty table, etc.
</blockquote></details>

Done.
___
*[internal/backend/sinktest/info.go, line 23 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNFIhm3iijcZpyQfGN:-MrO0oUl6-_KE-nFPkHk:bulkmt2) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/sinktest/info.go#L23)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

perhaps name this file dbinfo to match?
</blockquote></details>

I split out `db_info.go` and `table_info.go`.  Moved the relevant creation functions into those two files, as well.
___
*[internal/backend/sinktest/info.go, line 45 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNF8S98Nrc9uPsUXq1:-MrO2OVU4AMAlpPom8M1:bsjte78) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/sinktest/info.go#L45)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why no Create here?  Just Drop?
</blockquote></details>

See above comment.
___
*[internal/backend/apply/apply.go, line 162 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8ESRXDXJrJU121TFV:-MrNiFlA-NL_Wu-CHLsN:b-gj2er0) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L162)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is the assignment of j needed here? 
</blockquote></details>

Changed this to use a countdown loop instead.  The `pgx.Batch` type is opaque.
___
*[internal/backend/apply/apply.go, line 194 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8GNft3o0XK_pOo2oy:-MrNm0gA8EMxVISnvG1j:b-xxy25w) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L194)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

These seems slightly out of order.  I think they'll work, (delete something that doesn't exist,) but the logic doesn't flow cleanly.
</blockquote></details>

I reworked this to not use `delete()`, but to instead accumulate a set of known column names that are present in the incoming column data.  The variable names were expanded to make them easier to think through.
___
*[internal/backend/apply/apply.go, line 252 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8I2mA6A4ZXwqLshYu:-MrNnNi58J3padMrbgWO:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L252)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

why not 
for i, col := 

cleans up a lot of the colData[i] you're using all over all the place
</blockquote></details>

Done.
___
*[internal/backend/apply/apply.go, line 270 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8IF1x-dXm6KNEHPFR:-MrNnOVP5wh69TeIh9UU:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/apply.go#L270)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[internal/backend/apply/factory.go, line 39 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8jNJcDgETyGrElGab:-MrNpR1WAAKBrYvmmZKW:b-ei687p) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/apply/factory.go#L39)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I'm a little confused by the api here.

Get and New are the only exposed functions?

Get --> getUnlocked
New --> returns a factory

But no Create?
? --> createUnlocked

</blockquote></details>

`Get()` calls `createUnlocked()`.  I've renamed `createUnlocked()` to `getOrCreateUnlocked()` to be more explicit.
___
*[internal/backend/mutation/factory.go, line 43 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr8kGWLE1T5Gx9ykqEl:-MrNpZ2SBV0SRd-PuIf8:b-953gi0) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/mutation/factory.go#L43)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Are createUnlocked and getUnlocked called from anywhere else?  Do you need them to be their own functions?  I'm guessing for unit tests?
</blockquote></details>

They exist as two different functions because `getUnlocked()` is read-locked and `createUnlocked()` is write-locked.  The create method has been renamed and comments added to explain the differences in locking.
___
*[internal/backend/mutation/store.go, line 50 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-Mr92HqyBi5UpmRzcdmj:-MrNpmqnB6fxDQsJPGxl:b9ohtg) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/backend/mutation/store.go#L50)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Shouldn't this be New? 
</blockquote></details>

`ne [...]

2021-12-20 22:03 UTC, bobvawter reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73)* status: 20 of 55 files reviewed, 36 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[internal/frontend/cdc/resolved.go, line 128 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNIHee8UOto0iCkPAd:-MrOrXcm8Kl-Q7GOB_f4:bwoc8as) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/frontend/cdc/resolved.go#L128)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Revised the comment here that it's a filtering operation.
</blockquote></details>

Meant to say that I moved the filtering operation into the `Snapshot()` method, which now takes the user-defined schema as an argumunt.


<!-- Sent from Reviewable.io -->

2021-12-21 14:14 UTC, BramGruneir approved these changes
I had to look up TANSTAAFL.

> Reviewed 35 of 35 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-:-MrSKkla6BQd5EusrKf_:b-mdafsk)* status: all files reviewed, 4 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[internal/frontend/cdc/webhook.go, line 16 at r10](https://reviewable.io/reviews/cockroachdb/cdc-sink/73#-MrNK_Vb2VK5tRDFSEu_:-MrSIJUT7iyrdsFuOvUm:bb73djm) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/f4daee50f44949354615172e7a619f7635bb5ca2/internal/frontend/cdc/webhook.go#L16)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Supporting both really isn't that big of a deal, the difference is in the payload-decoder.  The bulk of the machinery is identical.  I also think we should strive to have compatibility with any CRDB release that's within the company's support window.
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2021-12-21 14:14 UTC, BramGruneir commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2021-12-21 14:24 UTC, merged