Kafka connector preview
cockroachdb/cdc-sink pull request #770
Opened 2024-03-15 13:30 UTC by sravotto

This PR consists of 3 separate commits:

- hlc: adding range.Contains function: adds a utility function to check if a range contains a given timestamp.
- Kafka connector preview: adds a source connector that consumes CockroachDB changefeeds send through a Kafka cluster
- Kafka connector integration test: verifies that change events originated by a CockroachDB changefeed, and routed via a single node Kafka cluster are received by the connector and applied to a target CockroachDB datatabase.

2024-03-15 17:10 UTC, BramGruneir requested changes
Overall, this is great, bit it needs a bit more work.

Also, I get that this is just the first pass here, but you're going to be limited by running only a single instance of replicator.  Ideally, we put the topics in staging and take out a lease against them to allow for more than one replicator instance to push data.
I can see how this can be easily be done by running multiple instances of ConsumeClaim.  Or we can use the mark function to determine if a value has been already processed.  Lots of options here.

> Reviewed 2 of 2 files at r1, 13 of 13 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-:-Nt22I4I6reKjmTlb3WG:b-jo4f9h)* status: all files reviewed, 21 unresolved discussions (waiting on @bobvawter and @sravotto)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1u1Lq-gbrJZlC1_Yt):*
sent not send
___
*[`internal/source/kafka/config.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1yMkV1SpM6Jmr3BFK:-Nt1yMkV1SpM6Jmr3BFL:bthykdq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L74)):*
> ```Go
> 	f.IntVar(&c.batchSize, "batchSize", 100, "messages to accumulate before committing to the target")
> 	f.StringArrayVar(&c.brokers, "broker", nil, "address of Kafka broker(s)")
> 	f.StringVar(&c.from, "from", "", "accept messages at or newer than this timestamp")
> ```

From and To or Min and Max?  Also, perhaps it's worth adding Timestamp to the end of it for clarity:  FromTimestamp  or MinTimestamp  

I think Min and Max might be better.

Just because from could be from where or from when?
___
*[`internal/source/kafka/config.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zeyDBIKBrpE07_KZ:-Nt1zeyDBIKBrpE07_K_:b51b8qh) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L74)):*
> ```Go
> 	f.IntVar(&c.batchSize, "batchSize", 100, "messages to accumulate before committing to the target")
> 	f.StringArrayVar(&c.brokers, "broker", nil, "address of Kafka broker(s)")
> 	f.StringVar(&c.from, "from", "", "accept messages at or newer than this timestamp")
> ```

only accept messages with timestamps at or newer than this timestamp, this is an inclusive lower limit
___
*[`internal/source/kafka/config.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1yx8J3d7siBFFWm3u:-Nt1yx8J3d7siBFFWm3v:bdy2zza) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L76)):*
> ```Go
> 	f.StringVar(&c.from, "from", "", "accept messages at or newer than this timestamp")
> 	f.StringVar(&c.group, "group", "", "the Kafka consumer group id")
> 	f.BoolVar(&c.oldest, "oldest", false, "start from the oldest message available")
> ```

Mention that this is in lieu of --From (and vice versa in --From)
___
*[`internal/source/kafka/config.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zPtWDZ58woD3bcNR:-Nt1zPtWDZ58woD3bcNS:b-r9b2si) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L76)):*
> ```Go
> 	f.StringVar(&c.from, "from", "", "accept messages at or newer than this timestamp")
> 	f.StringVar(&c.group, "group", "", "the Kafka consumer group id")
> 	f.BoolVar(&c.oldest, "oldest", false, "start from the oldest message available")
> ```

Should this also be set to true by default?
___
*[`internal/source/kafka/config.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zTtN-5dL8LirxKK3:-Nt1zTtN-5dL8LirxKK4:bg99io1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L78)):*
> ```Go
> 	f.BoolVar(&c.oldest, "oldest", false, "start from the oldest message available")
> 	f.StringVar(&c.strategy, "strategy", "sticky", "Kafka consumer group re-balance strategy")
> 	f.StringVar(&c.to, "to", "", "accept messages at or older than this timestamp")
> ```

only accept messages with timestamps before this one, this is an exclusive upper limit
___
*[`internal/source/kafka/config.go` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1ynZK0Wdr8PC4bkXU:-Nt1ynZK0Wdr8PC4bkXV:biwvyop) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L80)):*
> ```Go
> 	f.StringVar(&c.to, "to", "", "accept messages at or older than this timestamp")
> 	f.StringArrayVar(&c.topics, "topic", nil, "the topic(s) that the consumer should use")
> 	f.StringVar(&c.version, "kafkaVersion", "3.6.0", "Kafka version")
> ```

Why is this necessary?
___
*[`internal/source/kafka/config.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1z9Gy4gcRXmmen-Hx:-Nt1z9Gy4gcRXmmen-Hy:bqi7ad0) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L131)):*
> ```Go
> 	}
> 	if hlc.Compare(from, to) > 0 {
> 		return errors.New("from timestamp must earlier than to timestamp")
> ```

this message is unclear
___
*[`internal/source/kafka/conn.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt2-2khBGJg9xAAy79l:-Nt2-2khBGJg9xAAy79m:b-20rg8q) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L35)):*
> ```Go
> //
> //	note: we get resolved timestamps on all the partitions,
> //	      so we should be able to leverage that.
> ```

There may be some complication here, as the messages are only ordered per partition right?  Or is it by topic?  So we may need to wait on writing a resolved timestamp until after we've grabbed all the other messages
___
*[`internal/source/kafka/conn.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zy5y8evHpl89-dCb:-Nt1zy5y8evHpl89-dCc:b-y245ak) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L38)):*
> ```Go
> //
> // TODO (silvano): support Avro format, schema registry.
> // TODO (silvano): add metrics.
> ```

Please add github issues for these todos and link the issue number here
___
*[`internal/source/kafka/conn.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt20qrf0cAVUtcFRGpq:-Nt20qrf0cAVUtcFRGpr:b-rcp4of) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L62)):*
> ```Go
> // are allocated to each process based on the chosen rebalance strategy.
> func (c *Conn) Start(ctx *stopper.Context) error {
> 	version, err := sarama.ParseKafkaVersion(c.config.version)
> ```

This check should be in preflight.
___
*[`internal/source/kafka/conn.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt20YQy4OIubZNKd4Cn:-Nt20YQy4OIubZNKd4Co:bzd01x1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L74)):*
> ```Go
> 
> 	switch c.config.strategy {
> 	case "sticky":
> ```

This initial check should be in preflight.  And please make it an enum.
___
*[`internal/source/kafka/conn.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt219zg6jdHLS0xWaO4:-Nt219zg6jdHLS0xWaO5:bbst7ys) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L133)):*
> ```Go
> // getOffsets get the most recent offsets at the given time
> // for all the topics and partitions.
> // TODO (silvano) : add testing
> ```

Add github issue and ref to it here please
___
*[`internal/source/kafka/conn.go` line 136 at r2](https://reviewable.io/revie [...]

2024-03-15 20:31 UTC, sravotto reviewed
The way ConsumerGroup works allow multiple instances of replicator.  Each instance would have its own set of (non-overlapping) partitions. And if one replicator dies, its partitions will be allocated to the remaining ones. It works fine with immediate, but we need some coordination with the resolved timestamps across replication instances if we want to enforce transaction consistency.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-:-Nt28_xi1cp7YdvcXW34:b-ebjpll)* status: 10 of 19 files reviewed, 21 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1u1Lq-gbrJZlC1_Yt):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

sent not send
</blockquote></details>

Done.
___
*[`internal/source/kafka/config.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1yMkV1SpM6Jmr3BFK:-Nt2MbGu4LEthB3riSga:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L74)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

From and To or Min and Max?  Also, perhaps it's worth adding Timestamp to the end of it for clarity:  FromTimestamp  or MinTimestamp  

I think Min and Max might be better.

Just because from could be from where or from when?
</blockquote></details>

Done.
___
*[`internal/source/kafka/config.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zeyDBIKBrpE07_KZ:-Nt2Mqh71oEWFdmkooAS:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L74)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

only accept messages with timestamps at or newer than this timestamp, this is an inclusive lower limit
</blockquote></details>

Done.
___
*[`internal/source/kafka/config.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1yx8J3d7siBFFWm3u:-Nt2MrjWBvXYyrNkWxd7:b-mg5wnr) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L76)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Mention that this is in lieu of --From (and vice versa in --From)
</blockquote></details>

I decided to remove oldest, since we have min,max. By default we'll start from the oldest available in Kafka.
___
*[`internal/source/kafka/config.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zPtWDZ58woD3bcNR:-Nt2N49z-kTSRnGZczSz:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L76)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Should this also be set to true by default?
</blockquote></details>

Done.
___
*[`internal/source/kafka/config.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zTtN-5dL8LirxKK3:-Nt2NDnP27HJ8sCGWujE:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L78)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

only accept messages with timestamps before this one, this is an exclusive upper limit
</blockquote></details>

Done.
___
*[`internal/source/kafka/config.go` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1ynZK0Wdr8PC4bkXU:-Nt2NVf2Bye1u6gK3ccT:b9ymuyk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L80)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

Removed for now. We'll add it later if it becomes necessary.
___
*[`internal/source/kafka/config.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1z9Gy4gcRXmmen-Hx:-Nt2NodTBrMpEzxOONJ_:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/config.go#L131)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

this message is unclear
</blockquote></details>

Done.
___
*[`internal/source/kafka/conn.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt2-2khBGJg9xAAy79l:-Nt27p9kDQsnyY7DqQvM:blyetm3) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L35)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

There may be some complication here, as the messages are only ordered per partition right?  Or is it by topic?  So we may need to wait on writing a resolved timestamp until after we've grabbed all the other messages
</blockquote></details>

Indeed. We have to receive the resolved timestamps from all the partitions.
___
*[`internal/source/kafka/conn.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt1zy5y8evHpl89-dCb:-Nt2awzw7V_p9bzxa5sk:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L38)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add github issues for these todos and link the issue number here
</blockquote></details>

Done.
___
*[`internal/source/kafka/conn.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt20qrf0cAVUtcFRGpq:-Nt2Nx7t-kpo9exISTlg:b-yv7qnk) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L62)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This check should be in preflight.
</blockquote></details>

Done. Removed version for now.
___
*[`internal/source/kafka/conn.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt20YQy4OIubZNKd4Cn:-Nt2O-ZhACb_vg0Xopaa:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L74)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This initial check should be in preflight.  And please make it an enum.
</blockquote></details>

Done.
___
*[`internal/source/kafka/conn.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt219zg6jdHLS0xWaO4:-Nt2ayW51HIkYnzoQll7:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L133)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Add github issue and ref to it here please
</blockquote></details>

Done.
___
*[`internal/source/kafka/conn.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt21hiwBtgKMltSbZXF:-Nt2OAJZ6-D1a-KANAED:b-wztg4t) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c98a3df1d8f67007/internal/source/kafka/conn.go#L136)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is there a pool or is this common practice?
</blockquote></details>

This is just used to get the offsets at the start. We are using a consumer group to get messages.
___
*[`internal/source/kafka/consumer.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt22Xa_-0MCRAnhdK6J:-Nt2PUZfAmQbE0YDa_eD:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/395886e3400c4cd504f15b51c9 [...]

2024-03-19 20:08 UTC, BramGruneir approved these changes
Makes sense.

@bobvawter, can you give this a review? 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 9 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-:-NtNK0sp5Zqsl3SAfi9g:b-7n4b0m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bobvawter)



<!-- Sent from Reviewable.io -->

2024-03-20 19:43 UTC, sravotto reviewed
Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-:-NtSJuJY3rR-GISSWkYR:b1xog4q)* status: 6 of 19 files reviewed, 8 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/kafka/config.go` line 48 at r3](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-Nt2Czj58Af7iA2-RYBm:-NtRb-pZ4wsEryc_0FY0:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/c47f2b5b2b55cc9da1a71b73025b92da92f3e156/internal/source/kafka/config.go#L48)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If these fields are exported, you can take this whole object and publish it to the Diagnostics endpoint as a trivially JSON-ish object.
</blockquote></details>

Done.
___
*[`internal/source/kafka/consumer.go` line 80 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtR70Nf9JXEll_z9jv2:-NtRazx--yJlQ81A64NU:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/source/kafka/consumer.go#L80)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Use `log.WithError(err).Level("....")` here and elsewhere. That allows the log handler to access the structure (and stack) of the error message.  Also, errors are typically used with the `%v` verb, which allows the object to format itself.

Also, anywhere you call an external API that returns an error should have an `errors.WithStack()` on it.
</blockquote></details>

Done.
___
*[`internal/source/kafka/consumer.go` line 141 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtR82HMChX347Lh5VZ9:-NtRaxF5CZZqOO1ukvNA:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/source/kafka/consumer.go#L141)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why does this return a new map?
</blockquote></details>

Done.
___
*[`internal/source/kafka/consumer.go` line 147 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtR8HE92HdZNOhg7aus:-NtRawqp2SCGRXv74gbn:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/source/kafka/consumer.go#L147)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why does this method return a batch?
</blockquote></details>

Done.
___
*[`internal/source/kafka/consumer.go` line 164 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtR8RXh3jlApl1rzmIY:-NtSJxjYCW3aTP-0lHcC:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/source/kafka/consumer.go#L164)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Consider Postel's law.
</blockquote></details>

Done.
___
*[`internal/source/kafka/integration_test.go` line 53 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtR9R3P3gRzTmRFYnjp:-NtSJnG36gMiKR-eh2kJ:b1go6h7) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/source/kafka/integration_test.go#L53)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I'd like to see a version of this test that's driven by a `seqtest.Generator`.  It will generate a non-trivial sequence of mutations and also validate that the data in the target tables has maintained the correct order of updates. You should be able to use the `GenerateInto(batch)` and `CheckConsistent()` methods to bookend the Kafka transport code.
</blockquote></details>

Filed https://github.com/cockroachdb/cdc-sink/issues/789
___
*[`internal/source/kafka/provider.go` line 46 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtRAOr515X8UTYclDm7:-NtRanuy3pL-nhkQfxwY:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/source/kafka/provider.go#L46)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Inject `switcher.Switcher` instead and leave it in `ModeImmediate`. It will build a complete sequencer stack for you and provides a faster on-ramp to supporting more that just immediate mode.
</blockquote></details>

Done.
___
*[`internal/util/hlc/hlc_test.go` line 58 at r6](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtRB3Vy6S3KDIZY45EM:-NtRanLEEUpBHc4i-vtH:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dd5920a8bdc493f9761cd7ea0ff508c624cedd34/internal/util/hlc/hlc_test.go#L58)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Write these as `ten.Before()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-21 19:23 UTC, bobvawter approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> w/ a couple of nits

> Reviewed 1 of 13 files at r2, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-:-NtXSt8B5UIj3XF6TDie:b83sw0r)* status: all files reviewed, 2 unresolved discussions (waiting on @sravotto)

___
*[`internal/source/kafka/conn.go` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtX4CCGDO_B3kAoYwhD:-NtX4CCGDO_B3kAoYwhE:b-saw0ee) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/188d0e87db19b3047f4a28002762ac8a83ad86bd/internal/source/kafka/conn.go#L69)):*
> ```Go
> // are allocated to each process based on the chosen rebalance strategy.
> func (c *Conn) Start(ctx *stopper.Context) (err error) {
> 	/**
> ```

Switch block comment to line comments and reflow.
___
*[`internal/source/kafka/provider.go` line 59 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtX2d84CYynA0BPIocd:-NtX2d84CYynA0BPIoce:bm8lj4a) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/188d0e87db19b3047f4a28002762ac8a83ad86bd/internal/source/kafka/provider.go#L59)):*
> ```Go
> 	mode := notify.VarOf(switcher.ModeImmediate)
> 	sw = sw.WithMode(mode)
> 	// seq, err := scriptSeq.Wrap(ctx, sw)
> ```

Dead code.


<!-- Sent from Reviewable.io -->

2024-03-21 19:58 UTC, sravotto reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-:-NtX_wEg48q-JhYNCO7a:b-ucfknh)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @bobvawter)

___
*[`internal/source/kafka/conn.go` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtX4CCGDO_B3kAoYwhD:-NtX_tRs5N0NdVQdtGe2:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/188d0e87db19b3047f4a28002762ac8a83ad86bd/internal/source/kafka/conn.go#L69)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Switch block comment to line comments and reflow.
</blockquote></details>

Done.
___
*[`internal/source/kafka/provider.go` line 59 at r7](https://reviewable.io/reviews/cockroachdb/cdc-sink/770#-NtX2d84CYynA0BPIocd:-NtX_t0G2S7zESkSlSXy:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/188d0e87db19b3047f4a28002762ac8a83ad86bd/internal/source/kafka/provider.go#L59)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Dead code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-21 20:22 UTC, merged