kafka: finding proper offset to start replay, given a min timestamp
cockroachdb/cdc-sink pull request #824
Opened 2024-04-16 15:29 UTC by sravotto

This change improves the logic to find an adequate offset to start the event replay. We return the offset of the most recent resolved timestamp message that is stricly less than the minimum timestamp provided by the user.

A new set of metrics have been added to track the total number of messages that have been replayed, and the number of messages read to find the resolved timestamp.

A new mock client and consumer have been introduced to facilitate testing.

2024-04-23 14:11 UTC, sravotto reviewed
Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-:-NwAI2hE-eaRHsw6l88u:b1xog4q)* status: 9 of 14 files reviewed, 9 unresolved discussions (waiting on @bobvawter, @BramGruneir, and @github-advanced-security[bot])

___
*[`internal/source/kafka/config.go` line 100 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvljAIJAoxqQq-iNr7z:-Nw6DRn83qdb6zzoOidS:bsa5goc) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/config.go#L100)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you add more details here please.  Add a warning that this MUST match the interval set in the CDC statement.  This is a weird configuration issue that people will mess up.

Call out the specific variable.  For example, do you mean min_checkpoint_frequency or resolved?

Also, rename this config parameter to exactly match the name of the one it needs to match.
</blockquote></details>

Done. There are 2 settings in the changefeeds that need to be set. This is just an optimization, so it's not a MUST.
___
*[`internal/source/kafka/consumer.go` line 162 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-Nvlp2Dj88eDj1YQjRn1:-Nw6D1Td7AyuycBwIhf-:b-pwv78b) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/dab2d2ccacbac1b6c237399b432d6ae3d7143538/internal/source/kafka/consumer.go#L162)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why is this no longer needed?
</blockquote></details>

moved to asPayload.
___
*[`internal/source/kafka/metrics.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvmS_NN1lnXmN-0ogE3:-Nw6D6aVCfcdc1HxbYxC:b-h84tjr) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/metrics.go#L26)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add these metrics to the grafana dashboard.
</blockquote></details>

Will do this later
https://github.com/cockroachdb/cdc-sink/issues/829
___
*[`internal/source/kafka/offset.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#gh-1567567931:-NvbhWp_4z94dDKoveVh:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e16f3dd7a9409ce7cba2632752c7502694deef26/internal/source/kafka/offset.go#L108)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Useless assignment to local variable

This definition of offset is never used.

[Show more details](https://github.com/cockroachdb/cdc-sink/security/code-scanning/18)
</blockquote></details>

Done.
___
*[`internal/source/kafka/offset.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvmTw0l6_UW2hlJjHyb:-Nw6DHAX-oOzuvcSWkBe:b6n5qia) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/offset.go#L67)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a github issue to track this.
</blockquote></details>

Done.  https://github.com/cockroachdb/cdc-sink/issues/830
___
*[`internal/source/kafka/offset.go` line 144 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-Nvrt67-622vmcsOUWwf:-Nw61pvs7iMVF_81nXNj:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/offset.go#L144)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why the break here?  Just add a comment.
</blockquote></details>

Done.
___
*[`internal/source/kafka/offset.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvrtFXU8QEiKKcwkEEH:-Nw61wEQ7d6drqScoKwo:bkdagoi) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/offset.go#L174)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add some comments so I can understand the logic here.
</blockquote></details>

Done. Turns out that there was a bug. If we don't find a suitable offset we should return offsetoldest.
___
*[`internal/source/kafka/payload.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-Nvrumt-BPbipRmiqywk:-Nw629KlA2-xfhbFOE5T:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/payload.go#L37)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Add unit test please.  I know it will be small, but still worth doing.
</blockquote></details>

Done.
___
*[`internal/source/kafka/mocks/client.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#gh-1567567927:-NvbhYMD5Oa1YMjAEgN0:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/e16f3dd7a9409ce7cba2632752c7502694deef26/internal/source/kafka/mocks/client.go#L73)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Expression has no effect

This expression has no effect.

[Show more details](https://github.com/cockroachdb/cdc-sink/security/code-scanning/17)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 15:24 UTC, BramGruneir requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/824)* status: all files reviewed, 6 unresolved discussions (waiting on @bobvawter, @github-advanced-security[bot], and @sravotto)

___
*[`internal/source/kafka/config.go` line 100 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvljAIJAoxqQq-iNr7z:-NwjZLXC2Wdi6icog8lT:b-ffuat5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/config.go#L100)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Done. There are 2 settings in the changefeeds that need to be set. This is just an optimization, so it's not a MUST.
</blockquote></details>

I'm still confused over this.  The two values are linked.  Do you mean the lowest of the two or or the largest?  
___
*[`internal/source/kafka/offset.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvmTw0l6_UW2hlJjHyb:-NwjWm8L5iOC4K0DhJN2:bc2w8yl) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/offset.go#L67)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Done.  https://github.com/cockroachdb/cdc-sink/issues/830
</blockquote></details>

Please link it to this todo

// TODO (silvano) #830: make this parallel


<!-- Sent from Reviewable.io -->

2024-04-30 16:34 UTC, sravotto reviewed
Let me know if it is clearer...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-:-Nwjqfk3CKLpamYW6GlT:b-92k27z)* status: 12 of 14 files reviewed, 6 unresolved discussions (waiting on @bobvawter, @BramGruneir, and @github-advanced-security[bot])

___
*[`internal/source/kafka/config.go` line 100 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvljAIJAoxqQq-iNr7z:-Nwjpz7MAJOPLfcsZ1Kt:b-jzmui5) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/config.go#L100)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I'm still confused over this.  The two values are linked.  Do you mean the lowest of the two or or the largest?
</blockquote></details>

I added more information, however users should look at the change feed documentation.
___
*[`internal/source/kafka/offset.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-NvmTw0l6_UW2hlJjHyb:-NwjqYLx9-2fJDzn-yq9:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/4d564ecda316506a66b7922acbc93a41488f0614/internal/source/kafka/offset.go#L67)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please link it to this todo

// TODO (silvano) #830: make this parallel
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 20:08 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/824#-:-NwkbuyT-lERJ-DWDgBD:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @bobvawter and @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-04-30 20:23 UTC, merged