apply: Add multi-value SQL, benchmark
cockroachdb/cdc-sink pull request #87
Opened 2022-01-31 23:07 UTC by bobvawter

Note to reviewers, this depends on PR #86.

This change improves the throughput of the apply package by changing the SQL to
use multi-valued VALUE clauses.

The append benchmark is updated to demonstrate the performance curve of the
Apply method at varying batch sizes.

The default batch size is adjusted to 100 to be more conservative with total
size of generated SQL.

The testing GitHub workflow is updated to run on all branches and to add
another build step for this and future benchmarks.

Benchmark results on my laptop:

```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/cdc-sink/internal/target/apply
BenchmarkApply/size=1/base-10    	          199155	     60065 ns/op	268569.38 MB/s
BenchmarkApply/size=1/cas-10     	           76429	    161671 ns/op	38292.18 MB/s
BenchmarkApply/size=1/deadline-10         	  181066	     61327 ns/op	239148.64 MB/s
BenchmarkApply/size=1/cas+deadline-10     	   64364	    160838 ns/op	32414.52 MB/s
BenchmarkApply/size=10/base-10            	  130818	     99337 ns/op	1070802.78 MB/s
BenchmarkApply/size=10/cas-10             	   33937	    299548 ns/op	91768.23 MB/s
BenchmarkApply/size=10/deadline-10        	  124788	    106038 ns/op	956503.64 MB/s
BenchmarkApply/size=10/cas+deadline-10    	   43885	    299746 ns/op	118589.99 MB/s
BenchmarkApply/size=100/base-10           	   28309	    526175 ns/op	439461.58 MB/s
BenchmarkApply/size=100/cas-10            	    8474	   1447730 ns/op	47411.74 MB/s
BenchmarkApply/size=100/deadline-10       	   25753	    547519 ns/op	384049.86 MB/s
BenchmarkApply/size=100/cas+deadline-10   	    8410	   1443147 ns/op	47203.09 MB/s
BenchmarkApply/size=1000/base-10          	    2198	   5105932 ns/op	35123.07 MB/s
BenchmarkApply/size=1000/cas-10           	     854	  13761511 ns/op	5026.63 MB/s
BenchmarkApply/size=1000/deadline-10      	    2390	   5281912 ns/op	36933.60 MB/s
BenchmarkApply/size=1000/cas+deadline-10  	     853	  14189589 ns/op	4869.27 MB/s
BenchmarkApply/size=10000/base-10         	     234	  50549005 ns/op	3778.12 MB/s
BenchmarkApply/size=10000/cas-10          	      81	 144095278 ns/op	 455.32 MB/s
BenchmarkApply/size=10000/deadline-10     	     234	  51832442 ns/op	3684.56 MB/s
BenchmarkApply/size=10000/cas+deadline-10 	      85	 147260294 ns/op	 467.54 MB/s
```

2022-02-02 15:11 UTC, bobvawter commented
Rebased to `master` branch.

2022-02-03 16:08 UTC, BramGruneir requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/87)* status: all files reviewed, 5 unresolved discussions (waiting on @bobvawter and @sravotto)

___
*[internal/target/apply/apply.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-I4Q180_c8MW-L5Ok:-Mv-I4Q180_c8MW-L5Ol:b-syion1) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/apply.go#L188)):*
> ```Go
> 	tag, err := db.Exec(ctx, sql, allArgs...)
> 	if err != nil {
> 		return errors.Wrap(err, sql)
> ```

Do we have any concern over pii here?  Note that we shouldn't do anything right now, but we should start thinking about masking the actual data if needed.
___
*[internal/target/apply/templates.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KfMz8HrvJUqGyeYO:-Mv-KfMz8HrvJUqGyeYP:b-42zd6e) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L70)):*
> ```Go
> // at varying batch sizes. The map keys are just ints representing the
> // number of rows that the statement should process.
> type templateCache struct {
> ```

Isn't this over-optimized?  I can see wanting to cache them for 100 or whatever the batch size is, but not the smaller sizes.  Is the assumption that the batches will come in regularly at the same irregular sizes?
___
*[internal/target/apply/templates.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KGDp9n0vst7AGdfk:-Mv-JrMJ9OeKSEXwcp9Q:b-zdnr85) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L163)):*
> ```Go
> 	}
> 
> 	cpy := *t
> ```

why are you making a pointer to t here?
___
*[internal/target/apply/templates.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KZl4ExpnXb6GL4PF:-Mv-KZl4ExpnXb6GL4PG:b-rgt9vj) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L183)):*
> ```Go
> 	}
> 
> 	cpy := *t
> ```

here too.  Why the pointer to t?
___
*[internal/target/apply/queries/common.tmpl, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-JLit8MJGrrr7iCzU:-Mv-JLit8MJGrrr7iCzV:b-cd7ia6) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/queries/common.tmpl#L20)):*
> ```
>         (
>         {{- $needsComma := false }}
>         {{- range $pair := $pairs -}}
> ```

can't you use the range index instead of needscomma?  You did this above in names
___
*[internal/target/apply/queries/common.tmpl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-JJ7qDKK_UvwbFXcy:-Mv-JJ7qDKK_UvwbFXcz:b-8h75j6) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/queries/common.tmpl#L38)):*
> ```
>         (
>         {{- $needsComma := false }}
>         {{- range $pair := $pairs -}}
> ```

can't you use the range index instead of needscomma?


<!-- Sent from Reviewable.io -->

2022-02-03 16:21 UTC, bobvawter reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/87)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[internal/target/apply/templates.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KfMz8HrvJUqGyeYO:-Mv-Lt1o3FcOESUuC7zM:b-592ayp) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L70)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Isn't this over-optimized?  I can see wanting to cache them for 100 or whatever the batch size is, but not the smaller sizes.  Is the assumption that the batches will come in regularly at the same irregular sizes?
</blockquote></details>

I'm assuming that the row counts will likely be the batch size, 1, or some other small number, based on the source cluster's workload.  How about I split the difference and add a metric to track hit/miss rate so we can see if caching helps in real workloads?
___
*[internal/target/apply/templates.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KGDp9n0vst7AGdfk:-Mv-MTqLAAtkPwkrd2Za:b6ya1xf) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L163)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

why are you making a pointer to t here?
</blockquote></details>

I'm dereferencing `t` to make a copy that can be altered. The variable isn't named `copy`, because that conflicts with the built-in `copy()` function.  Added a comment to clarify.
___
*[internal/target/apply/templates.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KZl4ExpnXb6GL4PF:-Mv-M_IX9sydTcB_TSrc:bribihm) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L183)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

here too.  Why the pointer to t?
</blockquote></details>

As above.
___
*[internal/target/apply/queries/common.tmpl, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-JLit8MJGrrr7iCzU:-Mv-NNJmDx7kofX51hGW:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/queries/common.tmpl#L20)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

can't you use the range index instead of needscomma?  You did this above in names
</blockquote></details>

Done.
___
*[internal/target/apply/queries/common.tmpl, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-JJ7qDKK_UvwbFXcy:-Mv-NNkL9guvlIu5P_MM:b-896fix) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/queries/common.tmpl#L38)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

can't you use the range index instead of needscomma?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-08 18:50 UTC, BramGruneir approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cdc-sink/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sravotto)

___
*[internal/target/apply/templates.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cdc-sink/87#-Mv-KfMz8HrvJUqGyeYO:-MvPeavKBxauG5DnW9Ku:brxp9sq) ([raw file](https://github.com/cockroachdb/cdc-sink/blob/cf0347c059d9d771d736e02fcb82eece2abc1d57/internal/target/apply/templates.go#L70)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I'm assuming that the row counts will likely be the batch size, 1, or some other small number, based on the source cluster's workload.  How about I split the difference and add a metric to track hit/miss rate so we can see if caching helps in real workloads?
</blockquote></details>

Sounds good.


<!-- Sent from Reviewable.io -->

2022-02-08 18:56 UTC, merged